# -*- coding: utf-8 -*-
"""01_carga_microsoft_google.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfgTp6P2Eei7gYqWtolAqaTUr-UrmtFI

Conexion Base de datos Mongo
"""

from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["upme_solar_db"]
print("Conexión exitosa:", client.server_info()["version"])

from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["upme_solar_db"]
print("Conexión exitosa, versión:", client.server_info()["version"])
print("Colecciones existentes:", db.list_collection_names())

"""** Verificacion"""

from pymongo import MongoClient
import pandas as pd

client = MongoClient("mongodb://localhost:27017/")
db = client["upme_solar_db"]

"""Carga municipios pdet a Mongo"""

import geopandas as gpd
from pymongo import MongoClient
from datetime import datetime
import os

import sys
from pathlib import Path

# Agregar raíz del proyecto al path para importar config
sys.path.append(str(Path(__file__).resolve().parent.parent.parent))
from config import BASE
client = MongoClient("mongodb://localhost:27017/")
db = client["upme_solar_db"]
col = db["municipios_pdet"]
col.drop()

pdet = gpd.read_file(os.path.join(BASE, "semana_2", "datos", "procesados", "municipios_pdet.geojson"))

docs = []
for _, fila in pdet.iterrows():
    doc = {
        "cod_dane":       str(fila["cod_dane"]),
        "nombre":         fila["Municipio"],
        "departamento":   fila["Departamento"],
        "subregion_pdet": fila["SubPDET"],
        "area_km2":       float(fila["area_km2"]),
        "pdet":           True,
        "geometry":       fila["geometry"].__geo_interface__,
        "fuente":         "MGN2025",
        "cargado_en":     datetime.utcnow()
    }
    docs.append(doc)

col.insert_many(docs)
col.create_index([("geometry", "2dsphere")])
col.create_index([("cod_dane", 1)], unique=True)
print(f"municipios_pdet: {col.count_documents({})} documentos cargados")

"""Carga Microsoft a mongo"""

import pandas as pd
import json
from pymongo import MongoClient
from datetime import datetime
import os
import sys
from pathlib import Path

# Agregar raíz del proyecto al path para importar config
sys.path.append(str(Path(__file__).resolve().parent.parent.parent))
from config import BASE
client = MongoClient("mongodb://localhost:27017/")
db     = client["upme_solar_db"]
col    = db["ms_buildings"]
col.drop()
print("Colección limpia.")

csv_path   = os.path.join(BASE, "semana_3", "datos", "procesados", "microsoft_pdet_limpio.csv")
BATCH_SIZE = 1_000
total      = 0
errores    = 0
batch      = []

df = pd.read_csv(csv_path)
print(f"Total filas a cargar: {len(df)}")

for _, fila in df.iterrows():
    try:
        geom_str = fila["geometry"]

        # Si viene con escapes dobles, limpiarlos
        if isinstance(geom_str, str):
            geom_str = geom_str.replace('""', '"').strip('"')

        geom = json.loads(geom_str)

        doc = {
            "geometry":           geom,
            "area_m2":            float(fila["area_m2"]),
            "height":             float(fila["height"]),
            "cod_dane_municipio": None,
            "fuente":             "microsoft",
            "cargado_en":         datetime.utcnow()
        }
        batch.append(doc)

    except Exception as e:
        errores += 1
        if errores <= 3:  # mostrar solo los primeros 3 errores para debug
            print(f"  Error fila {_}: {e}")
            print(f"  Valor: {str(fila['geometry'])[:100]}")
        continue

    if len(batch) >= BATCH_SIZE:
        col.insert_many(batch)
        total += len(batch)
        batch = []
        print(f"  Insertados: {total:,}  |  Errores: {errores}")

if batch:
    col.insert_many(batch)
    total += len(batch)

print(f"\nCreando índices...")
col.create_index([("geometry", "2dsphere")])
col.create_index([("cod_dane_municipio", 1)])
print("Índices:", list(col.index_information().keys()))

print(f"\n✅ Carga completada")
print(f"   Total insertados: {total:,}")
print(f"   Errores:          {errores}")
print(f"   Total en MongoDB: {col.count_documents({}):,}")

"""Verificacion Carga de datos Mongo"""

print("=" * 50)
print("1. CONTEOS POR COLECCIÓN")
print("=" * 50)
for col in ["municipios_pdet", "ms_buildings", "goo_buildings"]:
    n = db[col].count_documents({})
    print(f"  {col}: {n:,} documentos")

print("\n" + "=" * 50)
print("2. ÍNDICES ACTIVOS")
print("=" * 50)
for col in ["municipios_pdet", "ms_buildings", "goo_buildings"]:
    indices = list(db[col].index_information().keys())
    print(f"  {col}: {indices}")

print("\n" + "=" * 50)
print("3. ESTADÍSTICAS DE ÁREA (area_m2)")
print("=" * 50)
for col in ["ms_buildings", "goo_buildings"]:
    stats = list(db[col].aggregate([{
        "$group": {
            "_id":          None,
            "total":        {"$sum": 1},
            "area_total":   {"$sum": "$area_m2"},
            "area_promedio":{"$avg": "$area_m2"},
            "area_max":     {"$max": "$area_m2"},
            "area_min":     {"$min": "$area_m2"}
        }
    }]))[0]
    print(f"\n  {col}:")
    print(f"    Total edificios:  {stats['total']:,}")
    print(f"    Área total:       {stats['area_total']:,.0f} m²")
    print(f"    Área promedio:    {stats['area_promedio']:.1f} m²")
    print(f"    Área máxima:      {stats['area_max']:.1f} m²")
    print(f"    Área mínima:      {stats['area_min']:.1f} m²")

print("\n" + "=" * 50)
print("4. PRUEBA ESPACIAL — punto en Tibú (municipio PDET)")
print("=" * 50)
punto_tibu = {"type": "Point", "coordinates": [-72.7317, 8.6572]}

mpio = db.municipios_pdet.find_one({
    "geometry": {"$geoIntersects": {"$geometry": punto_tibu}}
})
if mpio:
    print(f"  ✅ Municipio encontrado: {mpio['nombre']} — {mpio['departamento']}")
else:
    print("  ❌ No se encontró municipio — revisar índice")

print("\n" + "=" * 50)
print("5. TOP 5 MUNICIPIOS con más edificios (Google)")
print("=" * 50)
pipeline = [
    {"$match":  {"cod_dane_municipio": {"$ne": None}}},
    {"$group":  {"_id": "$cod_dane_municipio", "total": {"$sum": 1}}},
    {"$sort":   {"total": -1}},
    {"$limit":  5}
]
for r in db.goo_buildings.aggregate(pipeline):
    # Buscar nombre del municipio
    mpio = db.municipios_pdet.find_one({"cod_dane": r["_id"]})
    nombre = mpio["nombre"] if mpio else r["_id"]
    print(f"  {nombre}: {r['total']:,} edificios")

print("\n" + "=" * 50)
print("6. DISTRIBUCIÓN POR CONFIDENCE (Google)")
print("=" * 50)
pipeline = [
    {"$bucket": {
        "groupBy":    "$confidence",
        "boundaries": [0.7, 0.8, 0.9, 1.01],
        "default":    "otro",
        "output":     {"count": {"$sum": 1}}
    }}
]
for r in db.goo_buildings.aggregate(pipeline):
    print(f"  confidence {r['_id']}: {r['count']:,} edificios")

print("\n✅ Verificación completada")

from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["upme_solar_db"]

# Ver cuántos documentos tienen cod_dane_municipio sin ceros
problemas = db.goo_buildings.count_documents({
    "cod_dane_municipio": {"$regex": "^[0-9]{4}$"}
})
print(f"Documentos con código de 4 dígitos: {problemas:,}")

# Corregir — agregar cero al inicio
if problemas > 0:
    db.goo_buildings.update_many(
        {"cod_dane_municipio": {"$regex": "^[0-9]{4}$"}},
        [{"$set": {"cod_dane_municipio": {
            "$concat": ["0", "$cod_dane_municipio"]
        }}}]
    )
    print("Códigos corregidos.")

    # Verificar corrección
    mpio = db.municipios_pdet.find_one({"cod_dane": "05837"})
    if mpio:
        print(f"Municipio 05837: {mpio['nombre']}")
    else:
        print("Municipio 05837: No encontrado")
else:
    print("No hay códigos con 4 dígitos — todo bien.")

pipeline = [
    {"$match":  {"cod_dane_municipio": {"$ne": None}}},
    {"$group":  {"_id": "$cod_dane_municipio", "total": {"$sum": 1}}},
    {"$sort":   {"total": -1}},
    {"$limit":  5}
]
print("TOP 5 MUNICIPIOS con más edificios (Google) — corregido:")
for r in db.goo_buildings.aggregate(pipeline):
    mpio = db.municipios_pdet.find_one({"cod_dane": r["_id"]})
    nombre = mpio["nombre"] if mpio else f"SIN NOMBRE ({r['_id']})"
    print(f"  {nombre}: {r['total']:,} edificios")

# Verificar que no quedan códigos de 4 dígitos
restantes = db.goo_buildings.count_documents({
    "cod_dane_municipio": {"$regex": "^[0-9]{4}$"}
})
print(f"\nCódigos de 4 dígitos restantes: {restantes}")